# vim: ts=2:sts=2:sw=2:expandtab

version: '3'

services:
  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro:6.3.13
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/seafile:/shared
    environment:
      - SEAFILE_SERVER_HOSTNAME=file.serubin.net
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=files.serubin.net"
      - "traefik.frontend.rule=Host: files.serubin.net"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

  onlyoffice:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/onlyoffice/logs:/var/log/onlyoffice
      - /opt/data/onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/data/onlyoffice/lib:/var/lib/onlyoffice
      - /opt/data/onlyoffice/db:/var/lib/postgresql
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=docs.serubin.net"
      - "traefik.frontend.rule=Host: docs.serubin.net"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

networks:
  traefik-public:
    external: true
