# vim: ts=2:sts=2:sw=2:expandtab

version: '3'

services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$SEAFILE_DB_PASSWORD  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/data/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - default

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    entrypoint: memcached -m 256
    networks:
      - default

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:7.0.13
    container_name: seafile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/seafile/data:/shared
    environment:
      - TIME_ZONE=America/Los_Angeles
      - DB_HOST=db
      - DB_ROOT_PASSWD=$SEAFILE_DB_PASSWORD
      - SEAFILE_SERVER_HOSTNAME=file.serubin.net
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=files.serubin.net"
      - "traefik.frontend.rule=Host: files.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    depends_on:
      - db
      - memcached

  onlyoffice:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/onlyoffice/logs:/var/log/onlyoffice
      - /opt/data/onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/data/onlyoffice/lib:/var/lib/onlyoffice
      - /opt/data/onlyoffice/db:/var/lib/postgresql
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=docs.serubin.net"
      - "traefik.frontend.rule=Host: docs.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

networks:
  traefik-public:
    external: true
