# vim: ts=2:sts=2:sw=2:expandtab

version: '3'

services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$SEAFILE_DB_PASSWORD
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/data/seafile/db:/var/lib/mysql
    networks:
      - default

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    entrypoint: memcached -m 256
    networks:
      - default

  elasticsearch:
    image: seafileltd/elasticsearch-with-ik:5.6.16
    container_name: seafile-elasticsearch
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /opt/data/seafile/elasticsearch:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - default


  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/seafile:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=$SEAFILE_DB_PASSWORD
      - TIME_ZONE=America/Los_Angeles
      - SEAFILE_SERVER_HOSTNAME=file.serubin.net
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD
      - SEAFILE_SERVER_LETSENCRYPT=false  # Handled by traefik
    networks:
      - default
      - traefik-public
    depends_on:
      - db
      - memcached
      - elasticsearch
    labels:
      - "traefik.enable=true"
      - "traefik.domain=files.serubin.net"
      - "traefik.frontend.rule=Host: files.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

  onlyoffice:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /opt/data/onlyoffice/logs:/var/log/onlyoffice
      - /opt/data/onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/data/onlyoffice/lib:/var/lib/onlyoffice
      - /opt/data/onlyoffice/db:/var/lib/postgresql
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=docs.serubin.net"
      - "traefik.frontend.rule=Host: docs.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

networks:
  traefik-public:
    external: true
